### ISSUE TITLE
ScureCRT 9.6

### ISSUE THREAD

**Issue by m1ngf3i** [HyperSine/how-does-SecureCRT-encrypt-password#6]
ScureCRT 9.6
securecrt_cipher.py dec -2 --prefix 02 77*******

raise ValueError('Bad ciphertext: incorrect padding.')
ValueError: Bad ciphertext: incorrect padding.

**Comment by HyperSine** [comment]
Maybe you have set config passphrase in your SecureCRT. If it is, add `-p <your config passphrase>` option to your command line. If not, would you mind paste the full encrypted password here? Otherwise, I cannot debug the script and figure out what's wrong.

By the way, does SecureCRT has 9.6 version until today (2023/09/07)? I looked at www.vandyke.com. It has only 9.4.

**Comment by m1ngf3i** [comment]
S:"Username"=admin
S:"Password V2"=02:771598e37884ecc946b94c5481a4261c1ab2662ba90dbbb201e4ce74de27a9e00b900f3daadb35634618c3f31fefd4ed8ad76637779dea8f6cc711fa70989417
S:"Login Script V3"=02:69ed0d0044bfb68ab8e3b851eeb862e99806502e56eb5d9295733b1fbe04e6937505888812e6acd43ae0c6b6df510f27
thanks

**Comment by HyperSine** [comment]
I just updated securecrt_cipher.py. Your password should be able to decrypt.

**Comment by m1ngf3i** [comment]
thanks！
